target 'Keeping' do

  pod 'DateTools'
  pod 'DZNEmptyDataSet'
  pod 'FSCalendar'
  pod 'FMDB'
  pod 'BEMCheckBox'
  pod 'FDFullscreenPopGesture'
  pod 'AMPopTip', '~> 1.5'
  pod 'AVOSCloud'
  pod 'IQKeyboardManager'
  pod 'IDMPhotoBrowser'
  pod 'MGSwipeTableCell'
  pod 'SVProgressHUD'
  pod 'VTAcknowledgementsViewController' 
  pod 'Bugly'

end

target 'KeepingWidget' do
	
  pod 'FMDB'
  pod 'DateTools'
  pod 'BEMCheckBox'
  pod 'DZNEmptyDataSet'

end