target 'Keeping' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Keeping
  pod 'MBProgressHUD'
  pod 'Appirater'
  pod 'DateTools'
  pod 'DZNEmptyDataSet'
  pod 'FSCalendar'
  pod 'FMDB'
  pod 'BEMCheckBox'
  pod 'AVOSCloud'
end
