target 'Keeping' do

  pod 'MBProgressHUD'
  pod 'Appirater'
  pod 'DateTools'
  pod 'DZNEmptyDataSet'
  pod 'FSCalendar'
  pod 'FMDB'
  pod 'BEMCheckBox'
  pod 'AVOSCloud'
  pod 'HSDatePickerViewController'
  pod 'FDFullscreenPopGesture'
  pod 'YFStartView'
  pod 'AMPopTip'
  
end

target 'KeepingWidget' do
	
  pod 'FMDB'
  pod 'DateTools'
  pod 'BEMCheckBox'
  pod 'DZNEmptyDataSet'

end

target 'KeepingWatch' do
  
  pod 'FMDB'
  pod 'DateTools'

end

target 'KeepingWatch Extension' do
  
  pod 'FMDB'
  pod 'DateTools'

end